### ISSUE TITLE
change css?

### ISSUE THREAD

**Issue by floswald** [piever/Remark.jl#6]
this is a question, not an issue. how could i change the css for the presentation? say i wanted to use this template

https://gist.github.com/floswald/2bda97f3428a6b4fc26828b32f21b931

I saw that in the genereated html you have 

```
    <link rel="stylesheet" type="text/css" href="styles.css">
```

and so i saved the gist above to `build/styles.css`. indeed the fonts changed. is that a way you would recommend to do this?

**Comment by piever** [comment]
It's not really implemented yet. A possible plan is as follows:

- Move the inline css to a separate file that goes in the build by default
- Allow a `css = ...` keyword argument where you can put the location of your custom css to be used instead of the default

Does this solve your use case? The way you're doing now has the disadvantage that a new build will cancel your css so you have to redo it very time...

**Comment by piever** [comment]
If you pull master you can try: `slideshow(args...; css = "path/to/custom/css")` and it should just work, let me know if there are issues.

**Comment by piever** [comment]
I'll soon merge a branch that breaks 0.6 compatibility, so this is the 0.6 compatible commit with the css feature:

https://github.com/piever/Remark.jl/commit/be5d5f85d36c14c75324381d0836e72dfbd8dfa5

**Comment by floswald** [comment]
works perfectly, thanks.
